CREATE TABLE IF NOT EXISTS strategies (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    description TEXT,
    raw_input   TEXT NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active   INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rules (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id INTEGER NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    indicator   TEXT NOT NULL,
    operator    TEXT NOT NULL,
    value       REAL,
    value_text  TEXT,
    timeframe   TEXT DEFAULT 'daily',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS watchlist (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id INTEGER NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    symbol      TEXT NOT NULL,
    added_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(strategy_id, symbol)
);

CREATE TABLE IF NOT EXISTS alerts (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id  INTEGER NOT NULL REFERENCES strategies(id),
    symbol       TEXT NOT NULL,
    rule_id      INTEGER REFERENCES rules(id),
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    signal_data  TEXT,
    is_read      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS analysis_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT NOT NULL,
    recommendation  TEXT NOT NULL,
    reasoning       TEXT,
    trend           TEXT,
    confidence      REAL,
    source          TEXT,
    screening_data  TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_analysis_symbol ON analysis_history(symbol);
CREATE INDEX IF NOT EXISTS idx_analysis_created ON analysis_history(created_at DESC);

-- ============================================================
-- TRADING ENGINE TABLES
-- ============================================================

-- Master trading configuration (single row, id=1)
CREATE TABLE IF NOT EXISTS trading_config (
    id                  INTEGER PRIMARY KEY DEFAULT 1,
    engine_enabled      INTEGER DEFAULT 0,          -- Master kill switch (0=off)
    paper_mode          INTEGER DEFAULT 1,           -- 1=paper, 0=live
    max_capital         REAL    DEFAULT 100000,      -- Default Rs.1L paper capital
    max_loss_per_trade  REAL    DEFAULT 35000,       -- Permissive for Rs.1L paper testing
    max_daily_loss      REAL    DEFAULT 50000,       -- Daily circuit breaker (Rs.)
    max_positions       INTEGER DEFAULT 3,           -- Max concurrent open positions
    risk_per_trade_pct  REAL    DEFAULT 35.0,        -- % of capital per trade (paper testing)
    scan_interval_min   INTEGER DEFAULT 5,           -- 5-minute scan interval
    strategies_enabled  TEXT    DEFAULT '["iron_condor","straddle_adjust","directional_spread"]',
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default config row on first run
INSERT OR IGNORE INTO trading_config (id) VALUES (1);

-- Trade proposals generated by evaluators (awaiting user approval)
CREATE TABLE IF NOT EXISTS trade_proposals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id     TEXT    NOT NULL,                -- "iron_condor", "straddle_adjust", etc.
    symbol          TEXT    NOT NULL,                -- "NIFTY" or "BANKNIFTY"
    direction       TEXT,                            -- "neutral", "bullish", "bearish"
    legs            TEXT    NOT NULL,                -- JSON array of leg definitions
    greeks          TEXT    DEFAULT '{}',            -- JSON: net delta, theta, etc.
    intelligence    TEXT    DEFAULT '{}',            -- JSON: VIX, PCR, IV%, expected move
    max_profit      REAL,
    max_loss        REAL,
    margin_needed   REAL,
    confidence      REAL,
    reasoning       TEXT,
    risk_checks     TEXT    DEFAULT '[]',            -- JSON array of 12 check results
    status          TEXT    DEFAULT 'pending',       -- pending | approved | rejected | executed | expired
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP,                       -- Auto-expire after 10 min if not actioned
    decided_at      TIMESTAMP                        -- When user approved/rejected
);

CREATE INDEX IF NOT EXISTS idx_proposals_status ON trade_proposals(status);
CREATE INDEX IF NOT EXISTS idx_proposals_created ON trade_proposals(created_at DESC);

-- Open and closed positions
CREATE TABLE IF NOT EXISTS positions (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    proposal_id      INTEGER REFERENCES trade_proposals(id),
    strategy_id      TEXT    NOT NULL,
    symbol           TEXT    NOT NULL,
    status           TEXT    DEFAULT 'open',          -- open | closed | stopped_out
    legs             TEXT    NOT NULL,                -- JSON array of filled order details
    entry_time       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    exit_time        TIMESTAMP,
    total_premium    REAL    DEFAULT 0,               -- Net premium collected (negative = debit)
    current_pnl      REAL    DEFAULT 0,               -- Live unrealized P&L
    realized_pnl     REAL    DEFAULT 0,               -- Final realized P&L on close
    stop_loss_level  REAL,
    target_level     REAL,
    adjustments      TEXT,                            -- Log of any position adjustments
    close_reason     TEXT,                            -- "target_hit", "sl_hit", "manual", "expiry"
    paper_mode       INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_positions_status ON positions(status);
CREATE INDEX IF NOT EXISTS idx_positions_symbol ON positions(symbol);

-- Daily P&L summary (one row per day for circuit breaker)
CREATE TABLE IF NOT EXISTS daily_pnl (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    date        TEXT    NOT NULL UNIQUE,              -- ISO date "YYYY-MM-DD"
    realized    REAL    DEFAULT 0,
    unrealized  REAL    DEFAULT 0,
    trade_count INTEGER DEFAULT 0,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_pnl_date ON daily_pnl(date DESC);

-- IV history for IV percentile calculation (one row per symbol per day)
CREATE TABLE IF NOT EXISTS iv_history (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol  TEXT    NOT NULL,
    date    TEXT    NOT NULL,                         -- ISO date "YYYY-MM-DD"
    atm_iv  REAL    NOT NULL,                         -- ATM IV as percentage (e.g., 14.5)
    vix     REAL    DEFAULT 0,
    UNIQUE(symbol, date)
);

CREATE INDEX IF NOT EXISTS idx_iv_history_symbol ON iv_history(symbol, date DESC);

-- Market events calendar for blackout detection
CREATE TABLE IF NOT EXISTS market_events (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    event_date      TEXT    NOT NULL,                 -- ISO date "YYYY-MM-DD"
    event_name      TEXT    NOT NULL,
    impact          TEXT    NOT NULL,                 -- "high", "medium", "low"
    category        TEXT,                             -- "rbi", "fed", "budget", "election"
    avoid_trading   INTEGER DEFAULT 0,                -- 1 = blackout day
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(event_date, event_name)
);

CREATE INDEX IF NOT EXISTS idx_market_events_date ON market_events(event_date);

-- Engine scan log (one row per scan cycle)
CREATE TABLE IF NOT EXISTS scan_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    scanned_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    market_data     TEXT,                             -- JSON summary of fetched data
    signals         TEXT    DEFAULT '[]',             -- JSON array of signals found
    blocked_reason  TEXT,                             -- Why no trades if applicable
    duration_ms     INTEGER                           -- Scan duration in milliseconds
);

-- Order log (every order placed, including unwinds, exits, adjustments)
CREATE TABLE IF NOT EXISTS order_log (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    position_id      INTEGER REFERENCES positions(id),
    order_type       TEXT    NOT NULL,                -- entry | exit | stop_loss | target | adjustment | unwind
    broker_order_id  TEXT,                            -- Zerodha order ID (NULL for paper)
    tradingsymbol    TEXT    NOT NULL,                -- e.g. NIFTY2540323500CE
    exchange         TEXT    DEFAULT 'NFO',
    transaction_type TEXT    NOT NULL,                -- BUY | SELL
    quantity         INTEGER NOT NULL,
    order_price      REAL,
    fill_price       REAL,
    status           TEXT    DEFAULT 'pending',       -- pending | placed | filled | cancelled | failed
    paper_mode       INTEGER DEFAULT 1,
    error_message    TEXT,
    placed_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    filled_at        TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_log_position ON order_log(position_id);

-- ============================================================
-- IT-BEAR MODULE ADDITIONS
-- ============================================================

-- Per-layer auto-execution toggle (appended to trading_config)
-- SQLite ALTER TABLE only allows ADD COLUMN, and only if column doesn't exist.
-- We use a safe migration pattern with INSERT OR IGNORE + UPDATE.
CREATE TABLE IF NOT EXISTS _migration_guard (
    migration_key TEXT PRIMARY KEY,
    applied_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add IT-bear layer toggle columns to trading_config (idempotent via trigger approach)
-- SQLite doesn't support IF NOT EXISTS on ALTER TABLE, so we catch errors in init_db().
-- These columns are declared here as documentation; actual migration is in database.py.

-- Earnings calendar cache
CREATE TABLE IF NOT EXISTS earnings_calendar (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol      TEXT    NOT NULL,
    earnings_date TEXT,
    fetched_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol)
);

CREATE INDEX IF NOT EXISTS idx_earnings_calendar_symbol ON earnings_calendar(symbol);

-- Earnings history (last 4 quarters per symbol)
CREATE TABLE IF NOT EXISTS earnings_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT    NOT NULL,
    period          TEXT    NOT NULL,
    revenue         REAL,
    earnings        REAL,
    eps             REAL,
    revenue_yoy_pct REAL,
    fetched_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol, period)
);

CREATE INDEX IF NOT EXISTS idx_earnings_history_symbol ON earnings_history(symbol, period);

-- Notification log (all channels)
CREATE TABLE IF NOT EXISTS notification_log (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    sent_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    type          TEXT    NOT NULL,      -- "trade_alert" | "daily_brief" | "risk_alert" | "test"
    channel       TEXT    NOT NULL,      -- "email" | "telegram" | "websocket"
    subject       TEXT,
    body          TEXT,
    success       INTEGER DEFAULT 0,     -- 1 = sent, 0 = failed / not configured
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_notification_log_sent ON notification_log(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_log_channel ON notification_log(channel, success);

-- ============================================================
-- LLM GATEWAY — cost observability + hard budget limits
-- ============================================================

-- Single-row config (id=1). All LLM calls obey these limits.
CREATE TABLE IF NOT EXISTS llm_config (
    id                  INTEGER PRIMARY KEY CHECK (id = 1),
    enabled             INTEGER DEFAULT 1,        -- master switch for all LLM features
    provider            TEXT    DEFAULT 'anthropic',  -- anthropic | openai | groq | gemini
    default_model       TEXT    DEFAULT 'claude-haiku-4-5-20251001',  -- cheapest capable by default
    daily_limit_usd     REAL    DEFAULT 1.0,      -- hard daily spend cap
    monthly_limit_usd   REAL    DEFAULT 10.0,     -- hard monthly spend cap
    per_call_max_tokens INTEGER DEFAULT 1500,     -- max output tokens per call
    calls_per_min       INTEGER DEFAULT 12,       -- rate limit
    cache_enabled       INTEGER DEFAULT 1,        -- response caching to avoid dup spend
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT OR IGNORE INTO llm_config (id) VALUES (1);

-- Every LLM call (or blocked attempt) is logged here for observability.
CREATE TABLE IF NOT EXISTS llm_usage (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    feature       TEXT,                  -- 'strategy_chat' | 'rule_parse' | 'analysis' | ...
    provider      TEXT,
    model         TEXT,
    input_tokens  INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cost_usd      REAL    DEFAULT 0,
    cached        INTEGER DEFAULT 0,     -- 1 if served from cache (cost 0)
    latency_ms    INTEGER,
    status        TEXT    DEFAULT 'ok',  -- ok | budget_blocked | rate_limited | disabled | error
    error         TEXT
);
CREATE INDEX IF NOT EXISTS idx_llm_usage_created ON llm_usage(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_llm_usage_feature ON llm_usage(feature);

-- Response cache (avoids paying twice for identical prompts).
CREATE TABLE IF NOT EXISTS llm_cache (
    cache_key   TEXT PRIMARY KEY,        -- sha256(provider|model|system|prompt|max_tokens)
    response    TEXT,
    model       TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- UNIFIED STRATEGIES (Phase B marketplace)
-- ============================================================

-- One row per strategy, regardless of source (predefined / custom / it-bear / llm-authored).
CREATE TABLE IF NOT EXISTS strategy_defs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    slug            TEXT UNIQUE,             -- stable id, e.g. 'iron_condor' or 'custom_17'
    name            TEXT NOT NULL,
    source          TEXT NOT NULL,           -- 'predefined' | 'it_bear' | 'custom' | 'llm'
    category        TEXT,                    -- 'options' | 'directional' | 'commodity' | 'event' | ...
    market          TEXT DEFAULT 'IN',       -- 'IN' | 'US' | 'BOTH'
    direction       TEXT,                    -- 'bullish' | 'bearish' | 'neutral' | 'any'
    description     TEXT,
    entry_conditions TEXT DEFAULT '[]',      -- JSON array of {indicator, operator, value, note}
    exit_conditions  TEXT DEFAULT '[]',      -- JSON array
    legs            TEXT DEFAULT '[]',       -- JSON array of option legs (if applicable)
    config          TEXT DEFAULT '{}',       -- JSON: tunable params (thresholds, sizing, time windows)
    risk            TEXT,                    -- 'low' | 'medium' | 'high'
    tags            TEXT DEFAULT '[]',       -- JSON array
    is_editable     INTEGER DEFAULT 1,       -- predefined originals are read-only (fork to edit)
    forked_from     TEXT,                    -- slug of parent if forked
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_strategy_defs_source ON strategy_defs(source);
CREATE INDEX IF NOT EXISTS idx_strategy_defs_category ON strategy_defs(category);

-- Chat history for LLM-assisted strategy authoring (per draft session).
CREATE TABLE IF NOT EXISTS strategy_chats (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id  TEXT NOT NULL,               -- groups messages of one authoring session
    role        TEXT NOT NULL,               -- 'user' | 'assistant'
    content     TEXT NOT NULL,
    draft       TEXT,                        -- JSON snapshot of the strategy draft after this turn
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_strategy_chats_session ON strategy_chats(session_id, created_at);
